name: Compilar APK

on:
  push:
    branches: [ "main", "master" ] # Se ejecutará cada vez que subas cambios a estas ramas
  workflow_dispatch: # Esto te permite activar la compilación manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar el código del repositorio
      uses: actions/checkout@v4

    - name: Configurar Java (JDK 17)
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        cache: 'gradle'

    - name: Dar permisos de ejecución a Gradle
      run: chmod +x ./gradlew

    - name: Compilar APK en modo Debug
      run: ./gradlew assembleDebug

    - name: Subir el APK resultante como artefacto
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk

